name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: knot
            asset_name: knot-linux-amd64
          - os: macos-latest
            artifact_name: knot
            asset_name: knot-macos-amd64
          - os: windows-latest
            artifact_name: knot.exe
            asset_name: knot-windows-amd64.exe

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        check-latest: true

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      run: go test -v ./...

    - name: Build
      run: |
        go build -v -o bin/${{ matrix.artifact_name }} cmd/knot/main.go

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: bin/${{ matrix.artifact_name }}
